language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - addon-google_apis-google-27

before_install:
  - yes | sdkmanager "platforms;android-27"
script: ./gradlew --stacktrace lint test :Demo:assembleDebug :Demo:assembleRelease
